//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatinCodeConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LatinCodeConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CodeConvert Name=&quot;ئۇيغۇرچىدىن ULY غا&quot; Descraption=&quot;ئۇيغۇر يېزىقىدىكى تېكىستلەرنى لاتىنچە يېزىلىشقا ئايلاندۇرىدۇ&quot; Author=&quot;سارۋان&quot;&gt;
        ///  &lt;Codes&gt;
        ///    &lt;code ReplaceCode=&quot;a&quot; SourceCode=&quot;ا&quot; isCompound=&quot;false&quot; &gt;&lt;/code&gt;
        ///    &lt;code ReplaceCode=&quot;b&quot; SourceCode=&quot;ب&quot; isCompound=&quot;false&quot; &gt;&lt;/code&gt;
        ///    &lt;code ReplaceCode=&quot;c&quot; SourceCode=&quot;چ&quot; isCompound=&quot;false&quot; &gt;&lt;/code&gt;
        ///    &lt;code ReplaceCode=&quot;d&quot; SourceCode=&quot;د&quot; isCompound=&quot;false&quot; &gt;&lt;/code&gt;
        ///    &lt;code ReplaceCode=&quot;e&quot; SourceCode=&quot;ە&quot; isCompo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UEY2ULY {
            get {
                return ResourceManager.GetString("UEY2ULY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CodeConvert Name=&quot;ULY2UEY&quot; Descraption=&quot;&quot; Author=&quot;Sarwan&quot;&gt;
        ///  &lt;Codes&gt;
        ///    &lt;code SourceCode=&quot;a&quot; ReplaceCode=&quot;ا&quot; isCompound=&quot;false&quot; &gt;&lt;/code&gt;
        ///    &lt;code SourceCode=&quot;b&quot; ReplaceCode=&quot;ب&quot; isCompound=&quot;false&quot; &gt;&lt;/code&gt;
        ///    &lt;code SourceCode=&quot;c&quot; ReplaceCode=&quot;چ&quot; isCompound=&quot;false&quot; &gt;&lt;/code&gt;
        ///    &lt;code SourceCode=&quot;d&quot; ReplaceCode=&quot;د&quot; isCompound=&quot;false&quot; &gt;&lt;/code&gt;
        ///    &lt;code SourceCode=&quot;e&quot; ReplaceCode=&quot;ە&quot; isCompound=&quot;false&quot; &gt;&lt;/code&gt;
        ///    &lt;code SourceCode=&quot;f&quot; ReplaceCode=&quot;ف&quot; isCompou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ULY2UEY {
            get {
                return ResourceManager.GetString("ULY2UEY", resourceCulture);
            }
        }
    }
}
